make transform-fmc-oas command and use prod tenant

diff --git a/scripts/cli b/scripts/cli
--- a/scripts/cli
+++ b/scripts/cli
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.5 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.3 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -34,7 +34,8 @@ cli_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Download and add public API YAML to the pubhub docs\n" "download"
+  printf "  %s   Download and add public API YAML to the pubhub docs\n" "download         "
+  printf "  %s   Perform transformations on FMC OAS and generate cdfmc-service-openapi.yaml\n" "transform-fmc-oas"
   echo
 
   # :command.long_usage
@@ -90,6 +91,40 @@ cli_download_usage() {
     # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  cli download\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cli_transform_fmc_oas_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "cli transform-fmc-oas - Perform transformations on FMC OAS and generate cdfmc-service-openapi.yaml\n"
+    echo
+
+  else
+    printf "cli transform-fmc-oas - Perform transformations on FMC OAS and generate cdfmc-service-openapi.yaml\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  cli transform-fmc-oas\n"
+  printf "  cli transform-fmc-oas --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  cli transform-fmc-oas\n"
     echo
 
   fi
@@ -187,10 +222,8 @@ cli_download_command() {
   root_dir=$(dirname $(dirname $(readlink -f "$0")))
   filename=openapi.yaml
   declare -A urls=(
-    ["public-api"]="https://edge.staging.cdo.cisco.com/api/platform/public-api/v3/api-docs.yaml"
-    ["object-service"]="https://edge.staging.cdo.cisco.com/api/platform/object-service/v3/api-docs.yaml"
-    # Currently dependent on the acme tenant cdFMC - need to update
-    ["cdFmc-service"]="https://cdo-acme.app.staging.cdo.cisco.com/api/api-explorer/fmc_oas3.json"
+      ["public-api"]="https://edge.staging.cdo.cisco.com/api/platform/public-api/v3/api-docs.yaml"
+      ["object-service"]="https://edge.staging.cdo.cisco.com/api/platform/object-service/v3/api-docs.yaml"
   )
 
   filenames=()
@@ -198,17 +231,12 @@ cli_download_command() {
       url=${urls[${service}]}
       filename="${service}-openapi.yaml"
       echo -n "$(yellow Downloading file from) $(yellow_underlined ${url}) to $(blue_bold ${root_dir}/${filename})... "
-      if [[ "$service" == "cdFmc-service" ]]; then
-          curl -s "$url" | \
-          # Replace cdFMC URLs with the new Public API proxy URL
-          jq '.paths |= with_entries(.key |= gsub("api/fmc_config/"; "v1/cdfmc/api/fmc_config/"))' | \
-          yq e -P - > "${root_dir}/${filename}"
-      else
-          curl -X GET --silent --url  "${url}" -o $root_dir/$filename
-          filenames+=("${root_dir}/${filename}")
-      fi
+      curl -X GET --silent --url  "${url}" -o $root_dir/$filename
+      filenames+=("${root_dir}/${filename}")
       echo "✅︎"
   done
+
+  filenames+=("${root_dir}/cdFmc-service-openapi.yaml")
 
   echo "$(yellow Installing redocly from npm)... "
   npm i
@@ -227,6 +255,29 @@ cli_download_command() {
       git push origin main
       cd -
   fi
+}
+
+# :command.function
+cli_transform_fmc_oas_command() {
+  # src/transform_fmc_oas_command.sh
+  root_dir=$(dirname $(dirname $(readlink -f "$0")))
+  filename=openapi.yaml
+  declare -A urls=(
+      # Currently dependent on the CDO_cisco-ai-team-cdo tenant cdFMC - need to update
+      ["cdFmc-service"]="https://cisco-ai-team-cdo.app.us.cdo.cisco.com/api/api-explorer/fmc_oas3.json"
+  )
+
+  filenames=()
+  for service in "${!urls[@]}"; do
+      url=${urls[${service}]}
+      filename="${service}-openapi.yaml"
+      echo -n "$(yellow Downloading file from) $(yellow_underlined ${url}) to $(blue_bold ${root_dir}/${filename})... "
+      curl -s "$url" | \
+      # Replace cdFMC URLs with the new Public API proxy URL
+      jq '.paths |= with_entries(.key |= gsub("api/fmc_config/"; "v1/cdfmc/api/fmc_config/"))' | \
+      yq e -P - > "${root_dir}/${filename}"
+      echo "✅︎"
+  done
 }
 
 # :command.parse_requirements
@@ -262,6 +313,13 @@ parse_requirements() {
       action="download"
       shift
       cli_download_parse_requirements "$@"
+      shift $#
+      ;;
+
+    transform-fmc-oas)
+      action="transform-fmc-oas"
+      shift
+      cli_transform_fmc_oas_parse_requirements "$@"
       shift $#
       ;;
 
@@ -352,6 +410,50 @@ cli_download_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+cli_transform_fmc_oas_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        cli_transform_fmc_oas_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="transform-fmc-oas"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -371,6 +473,7 @@ run() {
 
   case "$action" in
     "download") cli_download_command ;;
+    "transform-fmc-oas") cli_transform_fmc_oas_command ;;
   esac
 }
 
